/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentation.ContactEntryDTO();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ContactEntryDTO', function() {
    it('should create an instance of ContactEntryDTO', function() {
      // uncomment below and update the code to test ContactEntryDTO
      //var instane = new ApiDocumentation.ContactEntryDTO();
      //expect(instance).to.be.a(ApiDocumentation.ContactEntryDTO);
    });

    it('should have the property contactWith (base name: "contactWith")', function() {
      // uncomment below and update the code to test the property contactWith
      //var instane = new ApiDocumentation.ContactEntryDTO();
      //expect(instance).to.be();
    });

    it('should have the property customSymptom (base name: "customSymptom")', function() {
      // uncomment below and update the code to test the property customSymptom
      //var instane = new ApiDocumentation.ContactEntryDTO();
      //expect(instance).to.be();
    });

    it('should have the property customSymptomPresent (base name: "customSymptomPresent")', function() {
      // uncomment below and update the code to test the property customSymptomPresent
      //var instane = new ApiDocumentation.ContactEntryDTO();
      //expect(instance).to.be();
    });

    it('should have the property _date (base name: "date")', function() {
      // uncomment below and update the code to test the property _date
      //var instane = new ApiDocumentation.ContactEntryDTO();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new ApiDocumentation.ContactEntryDTO();
      //expect(instance).to.be();
    });

    it('should have the property examination (base name: "examination")', function() {
      // uncomment below and update the code to test the property examination
      //var instane = new ApiDocumentation.ContactEntryDTO();
      //expect(instance).to.be();
    });

  });

}));
