/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentation.LocationMatch();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LocationMatch', function() {
    it('should create an instance of LocationMatch', function() {
      // uncomment below and update the code to test LocationMatch
      //var instane = new ApiDocumentation.LocationMatch();
      //expect(instance).to.be.a(ApiDocumentation.LocationMatch);
    });

    it('should have the property endTimeMillis (base name: "endTimeMillis")', function() {
      // uncomment below and update the code to test the property endTimeMillis
      //var instane = new ApiDocumentation.LocationMatch();
      //expect(instance).to.be();
    });

    it('should have the property latitudeE7 (base name: "latitudeE7")', function() {
      // uncomment below and update the code to test the property latitudeE7
      //var instane = new ApiDocumentation.LocationMatch();
      //expect(instance).to.be();
    });

    it('should have the property longitudeE7 (base name: "longitudeE7")', function() {
      // uncomment below and update the code to test the property longitudeE7
      //var instane = new ApiDocumentation.LocationMatch();
      //expect(instance).to.be();
    });

    it('should have the property startTimeMillis (base name: "startTimeMillis")', function() {
      // uncomment below and update the code to test the property startTimeMillis
      //var instane = new ApiDocumentation.LocationMatch();
      //expect(instance).to.be();
    });

  });

}));
