/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentation.ModelAndView();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ModelAndView', function() {
    it('should create an instance of ModelAndView', function() {
      // uncomment below and update the code to test ModelAndView
      //var instane = new ApiDocumentation.ModelAndView();
      //expect(instance).to.be.a(ApiDocumentation.ModelAndView);
    });

    it('should have the property empty (base name: "empty")', function() {
      // uncomment below and update the code to test the property empty
      //var instane = new ApiDocumentation.ModelAndView();
      //expect(instance).to.be();
    });

    it('should have the property model (base name: "model")', function() {
      // uncomment below and update the code to test the property model
      //var instane = new ApiDocumentation.ModelAndView();
      //expect(instance).to.be();
    });

    it('should have the property modelMap (base name: "modelMap")', function() {
      // uncomment below and update the code to test the property modelMap
      //var instane = new ApiDocumentation.ModelAndView();
      //expect(instance).to.be();
    });

    it('should have the property reference (base name: "reference")', function() {
      // uncomment below and update the code to test the property reference
      //var instane = new ApiDocumentation.ModelAndView();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new ApiDocumentation.ModelAndView();
      //expect(instance).to.be();
    });

    it('should have the property view (base name: "view")', function() {
      // uncomment below and update the code to test the property view
      //var instane = new ApiDocumentation.ModelAndView();
      //expect(instance).to.be();
    });

    it('should have the property viewName (base name: "viewName")', function() {
      // uncomment below and update the code to test the property viewName
      //var instane = new ApiDocumentation.ModelAndView();
      //expect(instance).to.be();
    });

  });

}));
