/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentation.BasicErrorControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BasicErrorControllerApi', function() {
    describe('errorHtmlUsingDELETE', function() {
      it('should call errorHtmlUsingDELETE successfully', function(done) {
        //uncomment below and update the code to test errorHtmlUsingDELETE
        //instance.errorHtmlUsingDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('errorHtmlUsingGET', function() {
      it('should call errorHtmlUsingGET successfully', function(done) {
        //uncomment below and update the code to test errorHtmlUsingGET
        //instance.errorHtmlUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('errorHtmlUsingHEAD', function() {
      it('should call errorHtmlUsingHEAD successfully', function(done) {
        //uncomment below and update the code to test errorHtmlUsingHEAD
        //instance.errorHtmlUsingHEAD(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('errorHtmlUsingOPTIONS', function() {
      it('should call errorHtmlUsingOPTIONS successfully', function(done) {
        //uncomment below and update the code to test errorHtmlUsingOPTIONS
        //instance.errorHtmlUsingOPTIONS(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('errorHtmlUsingPATCH', function() {
      it('should call errorHtmlUsingPATCH successfully', function(done) {
        //uncomment below and update the code to test errorHtmlUsingPATCH
        //instance.errorHtmlUsingPATCH(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('errorHtmlUsingPOST', function() {
      it('should call errorHtmlUsingPOST successfully', function(done) {
        //uncomment below and update the code to test errorHtmlUsingPOST
        //instance.errorHtmlUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('errorHtmlUsingPUT', function() {
      it('should call errorHtmlUsingPUT successfully', function(done) {
        //uncomment below and update the code to test errorHtmlUsingPUT
        //instance.errorHtmlUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
