/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentation.DiaryControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DiaryControllerApi', function() {
    describe('deleteDiaryUsingDELETE', function() {
      it('should call deleteDiaryUsingDELETE successfully', function(done) {
        //uncomment below and update the code to test deleteDiaryUsingDELETE
        //instance.deleteDiaryUsingDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findDiariesUsingGET', function() {
      it('should call findDiariesUsingGET successfully', function(done) {
        //uncomment below and update the code to test findDiariesUsingGET
        //instance.findDiariesUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findDiaryUsingGET', function() {
      it('should call findDiaryUsingGET successfully', function(done) {
        //uncomment below and update the code to test findDiaryUsingGET
        //instance.findDiaryUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('saveDiaryUsingPOST', function() {
      it('should call saveDiaryUsingPOST successfully', function(done) {
        //uncomment below and update the code to test saveDiaryUsingPOST
        //instance.saveDiaryUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateDiaryUsingPUT', function() {
      it('should call updateDiaryUsingPUT successfully', function(done) {
        //uncomment below and update the code to test updateDiaryUsingPUT
        //instance.updateDiaryUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
