/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateDiaryDTO from '../model/CreateDiaryDTO';
import Diary from '../model/Diary';
import User from '../model/User';

/**
* DiaryController service.
* @module api/DiaryControllerApi
* @version 1.0
*/
export default class DiaryControllerApi {

    /**
    * Constructs a new DiaryControllerApi. 
    * @alias module:api/DiaryControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the deleteDiaryUsingDELETE operation.
     * @callback module:api/DiaryControllerApi~deleteDiaryUsingDELETECallback
     * @param {String} error Error message, if any.
     * @param {module:model/Diary} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes diary object
     * @param {Number} id id
     * @param {module:api/DiaryControllerApi~deleteDiaryUsingDELETECallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Diary}
     */
    deleteDiaryUsingDELETE(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteDiaryUsingDELETE");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = Diary;
      return this.apiClient.callApi(
        '/api/diaries/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the findDiariesUsingGET operation.
     * @callback module:api/DiaryControllerApi~findDiariesUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Diary} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Responds with a list of diaries
     * @param {module:api/DiaryControllerApi~findDiariesUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Diary}
     */
    findDiariesUsingGET(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = Diary;
      return this.apiClient.callApi(
        '/api/diaries', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the findDiaryUsingGET operation.
     * @callback module:api/DiaryControllerApi~findDiaryUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Diary} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Responds with a diary object
     * @param {Number} id id
     * @param {module:api/DiaryControllerApi~findDiaryUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Diary}
     */
    findDiaryUsingGET(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling findDiaryUsingGET");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = Diary;
      return this.apiClient.callApi(
        '/api/diaries/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the findUserUsingGET operation.
     * @callback module:api/DiaryControllerApi~findUserUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/User} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Responds with a diary object
     * @param {Number} id id
     * @param {module:api/DiaryControllerApi~findUserUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/User}
     */
    findUserUsingGET(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling findUserUsingGET");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = User;
      return this.apiClient.callApi(
        '/api/diaries/user/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the newDiaryUsingPOST operation.
     * @callback module:api/DiaryControllerApi~newDiaryUsingPOSTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Diary} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Saves new diary object
     * @param {module:model/CreateDiaryDTO} createDiaryDTO createDiaryDTO
     * @param {module:api/DiaryControllerApi~newDiaryUsingPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Diary}
     */
    newDiaryUsingPOST(createDiaryDTO, callback) {
      let postBody = createDiaryDTO;
      // verify the required parameter 'createDiaryDTO' is set
      if (createDiaryDTO === undefined || createDiaryDTO === null) {
        throw new Error("Missing the required parameter 'createDiaryDTO' when calling newDiaryUsingPOST");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = Diary;
      return this.apiClient.callApi(
        '/api/diaries/{id}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the replaceDiaryUsingPUT operation.
     * @callback module:api/DiaryControllerApi~replaceDiaryUsingPUTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Diary} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates a diary object
     * @param {Number} id id
     * @param {module:model/Diary} newDiary newDiary
     * @param {module:api/DiaryControllerApi~replaceDiaryUsingPUTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Diary}
     */
    replaceDiaryUsingPUT(id, newDiary, callback) {
      let postBody = newDiary;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling replaceDiaryUsingPUT");
      }
      // verify the required parameter 'newDiary' is set
      if (newDiary === undefined || newDiary === null) {
        throw new Error("Missing the required parameter 'newDiary' when calling replaceDiaryUsingPUT");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = Diary;
      return this.apiClient.callApi(
        '/api/diaries/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
