/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";

/**
* OperationHandler service.
* @module api/OperationHandlerApi
* @version 1.0
*/
export default class OperationHandlerApi {

    /**
    * Constructs a new OperationHandlerApi. 
    * @alias module:api/OperationHandlerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the handleUsingGET operation.
     * @callback module:api/OperationHandlerApi~handleUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * handle
     * @param {Object} opts Optional parameters
     * @param {Object.<String, {String: String}>} opts.body body
     * @param {module:api/OperationHandlerApi~handleUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    handleUsingGET(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/vnd.spring-boot.actuator.v3+json', 'application/json', 'application/vnd.spring-boot.actuator.v2+json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/actuator/health/**', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the handleUsingGET1 operation.
     * @callback module:api/OperationHandlerApi~handleUsingGET1Callback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * handle
     * @param {Object} opts Optional parameters
     * @param {Object.<String, {String: String}>} opts.body body
     * @param {module:api/OperationHandlerApi~handleUsingGET1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    handleUsingGET1(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/vnd.spring-boot.actuator.v3+json', 'application/json', 'application/vnd.spring-boot.actuator.v2+json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/actuator/health', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the handleUsingGET2 operation.
     * @callback module:api/OperationHandlerApi~handleUsingGET2Callback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * handle
     * @param {Object} opts Optional parameters
     * @param {Object.<String, {String: String}>} opts.body body
     * @param {module:api/OperationHandlerApi~handleUsingGET2Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    handleUsingGET2(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/vnd.spring-boot.actuator.v3+json', 'application/json', 'application/vnd.spring-boot.actuator.v2+json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/actuator/info', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
