/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";

/**
* WebMvcLinksHandler service.
* @module api/WebMvcLinksHandlerApi
* @version 1.0
*/
export default class WebMvcLinksHandlerApi {

    /**
    * Constructs a new WebMvcLinksHandlerApi. 
    * @alias module:api/WebMvcLinksHandlerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the linksUsingGET operation.
     * @callback module:api/WebMvcLinksHandlerApi~linksUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {Object.<String, {String: {String: Link}}>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * links
     * @param {module:api/WebMvcLinksHandlerApi~linksUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object.<String, {String: {String: Link}}>}
     */
    linksUsingGET(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/vnd.spring-boot.actuator.v3+json', 'application/json', 'application/vnd.spring-boot.actuator.v2+json'];
      let returnType = {'String': {'String': Link}};
      return this.apiClient.callApi(
        '/actuator', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
