/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Examination from './Examination';

/**
 * The ContactEntry model module.
 * @module model/ContactEntry
 * @version 1.0
 */
class ContactEntry {
    /**
     * Constructs a new <code>ContactEntry</code>.
     * All details about a contact entry.
     * @alias module:model/ContactEntry
     */
    constructor() { 
        
        ContactEntry.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ContactEntry</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ContactEntry} obj Optional instance to populate.
     * @return {module:model/ContactEntry} The populated <code>ContactEntry</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContactEntry();

            if (data.hasOwnProperty('contactWith')) {
                obj['contactWith'] = ApiClient.convertToType(data['contactWith'], 'String');
            }
            if (data.hasOwnProperty('customSymptom')) {
                obj['customSymptom'] = ApiClient.convertToType(data['customSymptom'], 'String');
            }
            if (data.hasOwnProperty('customSymptomPresent')) {
                obj['customSymptomPresent'] = ApiClient.convertToType(data['customSymptomPresent'], 'Boolean');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('examination')) {
                obj['examination'] = Examination.constructFromObject(data['examination']);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} contactWith
 */
ContactEntry.prototype['contactWith'] = undefined;

/**
 * @member {String} customSymptom
 */
ContactEntry.prototype['customSymptom'] = undefined;

/**
 * @member {Boolean} customSymptomPresent
 */
ContactEntry.prototype['customSymptomPresent'] = undefined;

/**
 * @member {Date} date
 */
ContactEntry.prototype['date'] = undefined;

/**
 * @member {String} description
 */
ContactEntry.prototype['description'] = undefined;

/**
 * @member {module:model/Examination} examination
 */
ContactEntry.prototype['examination'] = undefined;

/**
 * @member {Number} id
 */
ContactEntry.prototype['id'] = undefined;






export default ContactEntry;

