/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CorrespondenceDetailsDTO model module.
 * @module model/CorrespondenceDetailsDTO
 * @version 1.0
 */
class CorrespondenceDetailsDTO {
    /**
     * Constructs a new <code>CorrespondenceDetailsDTO</code>.
     * @alias module:model/CorrespondenceDetailsDTO
     */
    constructor() { 
        
        CorrespondenceDetailsDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CorrespondenceDetailsDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CorrespondenceDetailsDTO} obj Optional instance to populate.
     * @return {module:model/CorrespondenceDetailsDTO} The populated <code>CorrespondenceDetailsDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CorrespondenceDetailsDTO();

            if (data.hasOwnProperty('contactMethodType')) {
                obj['contactMethodType'] = ApiClient.convertToType(data['contactMethodType'], 'String');
            }
            if (data.hasOwnProperty('detail')) {
                obj['detail'] = ApiClient.convertToType(data['detail'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/CorrespondenceDetailsDTO.ContactMethodTypeEnum} contactMethodType
 */
CorrespondenceDetailsDTO.prototype['contactMethodType'] = undefined;

/**
 * @member {String} detail
 */
CorrespondenceDetailsDTO.prototype['detail'] = undefined;





/**
 * Allowed values for the <code>contactMethodType</code> property.
 * @enum {String}
 * @readonly
 */
CorrespondenceDetailsDTO['ContactMethodTypeEnum'] = {

    /**
     * value: "HOME"
     * @const
     */
    "HOME": "HOME",

    /**
     * value: "MOBILE"
     * @const
     */
    "MOBILE": "MOBILE",

    /**
     * value: "EMAIL"
     * @const
     */
    "EMAIL": "EMAIL"
};



export default CorrespondenceDetailsDTO;

