/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Duration model module.
 * @module model/Duration
 * @version 1.0
 */
class Duration {
    /**
     * Constructs a new <code>Duration</code>.
     * @alias module:model/Duration
     */
    constructor() { 
        
        Duration.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Duration</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Duration} obj Optional instance to populate.
     * @return {module:model/Duration} The populated <code>Duration</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Duration();

            if (data.hasOwnProperty('endTimestampMs')) {
                obj['endTimestampMs'] = ApiClient.convertToType(data['endTimestampMs'], 'Number');
            }
            if (data.hasOwnProperty('startTimestampMs')) {
                obj['startTimestampMs'] = ApiClient.convertToType(data['startTimestampMs'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} endTimestampMs
 */
Duration.prototype['endTimestampMs'] = undefined;

/**
 * @member {Number} startTimestampMs
 */
Duration.prototype['startTimestampMs'] = undefined;






export default Duration;

