/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ExaminationDTO model module.
 * @module model/ExaminationDTO
 * @version 1.0
 */
class ExaminationDTO {
    /**
     * Constructs a new <code>ExaminationDTO</code>.
     * All details about an examination.
     * @alias module:model/ExaminationDTO
     */
    constructor() { 
        
        ExaminationDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ExaminationDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ExaminationDTO} obj Optional instance to populate.
     * @return {module:model/ExaminationDTO} The populated <code>ExaminationDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExaminationDTO();

            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('dateOfExamination')) {
                obj['dateOfExamination'] = ApiClient.convertToType(data['dateOfExamination'], 'Date');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('streetname')) {
                obj['streetname'] = ApiClient.convertToType(data['streetname'], 'String');
            }
            if (data.hasOwnProperty('symptomDescription')) {
                obj['symptomDescription'] = ApiClient.convertToType(data['symptomDescription'], ['String']);
            }
            if (data.hasOwnProperty('symptomsID')) {
                obj['symptomsID'] = ApiClient.convertToType(data['symptomsID'], ['Number']);
            }
            if (data.hasOwnProperty('zipCode')) {
                obj['zipCode'] = ApiClient.convertToType(data['zipCode'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} city
 */
ExaminationDTO.prototype['city'] = undefined;

/**
 * @member {Date} dateOfExamination
 */
ExaminationDTO.prototype['dateOfExamination'] = undefined;

/**
 * @member {Number} id
 */
ExaminationDTO.prototype['id'] = undefined;

/**
 * @member {String} streetname
 */
ExaminationDTO.prototype['streetname'] = undefined;

/**
 * @member {Array.<String>} symptomDescription
 */
ExaminationDTO.prototype['symptomDescription'] = undefined;

/**
 * @member {Array.<Number>} symptomsID
 */
ExaminationDTO.prototype['symptomsID'] = undefined;

/**
 * @member {String} zipCode
 */
ExaminationDTO.prototype['zipCode'] = undefined;






export default ExaminationDTO;

