/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LocationMatch model module.
 * @module model/LocationMatch
 * @version 1.0
 */
class LocationMatch {
    /**
     * Constructs a new <code>LocationMatch</code>.
     * Describes match between two locations.
     * @alias module:model/LocationMatch
     */
    constructor() { 
        
        LocationMatch.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LocationMatch</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LocationMatch} obj Optional instance to populate.
     * @return {module:model/LocationMatch} The populated <code>LocationMatch</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LocationMatch();

            if (data.hasOwnProperty('endTimeMillis')) {
                obj['endTimeMillis'] = ApiClient.convertToType(data['endTimeMillis'], 'Number');
            }
            if (data.hasOwnProperty('latitudeE7')) {
                obj['latitudeE7'] = ApiClient.convertToType(data['latitudeE7'], 'Number');
            }
            if (data.hasOwnProperty('longitudeE7')) {
                obj['longitudeE7'] = ApiClient.convertToType(data['longitudeE7'], 'Number');
            }
            if (data.hasOwnProperty('startTimeMillis')) {
                obj['startTimeMillis'] = ApiClient.convertToType(data['startTimeMillis'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} endTimeMillis
 */
LocationMatch.prototype['endTimeMillis'] = undefined;

/**
 * @member {Number} latitudeE7
 */
LocationMatch.prototype['latitudeE7'] = undefined;

/**
 * @member {Number} longitudeE7
 */
LocationMatch.prototype['longitudeE7'] = undefined;

/**
 * @member {Number} startTimeMillis
 */
LocationMatch.prototype['startTimeMillis'] = undefined;






export default LocationMatch;

