/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Duration from './Duration';

/**
 * The PlaceVisit model module.
 * @module model/PlaceVisit
 * @version 1.0
 */
class PlaceVisit {
    /**
     * Constructs a new <code>PlaceVisit</code>.
     * @alias module:model/PlaceVisit
     */
    constructor() { 
        
        PlaceVisit.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PlaceVisit</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PlaceVisit} obj Optional instance to populate.
     * @return {module:model/PlaceVisit} The populated <code>PlaceVisit</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PlaceVisit();

            if (data.hasOwnProperty('centerLatE7')) {
                obj['centerLatE7'] = ApiClient.convertToType(data['centerLatE7'], 'Number');
            }
            if (data.hasOwnProperty('centerLngE7')) {
                obj['centerLngE7'] = ApiClient.convertToType(data['centerLngE7'], 'Number');
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = Duration.constructFromObject(data['duration']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} centerLatE7
 */
PlaceVisit.prototype['centerLatE7'] = undefined;

/**
 * @member {Number} centerLngE7
 */
PlaceVisit.prototype['centerLngE7'] = undefined;

/**
 * @member {module:model/Duration} duration
 */
PlaceVisit.prototype['duration'] = undefined;






export default PlaceVisit;

