/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SymptomDTO model module.
 * @module model/SymptomDTO
 * @version 1.0
 */
class SymptomDTO {
    /**
     * Constructs a new <code>SymptomDTO</code>.
     * All details about a symptom.
     * @alias module:model/SymptomDTO
     */
    constructor() { 
        
        SymptomDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SymptomDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SymptomDTO} obj Optional instance to populate.
     * @return {module:model/SymptomDTO} The populated <code>SymptomDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SymptomDTO();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('symptomType')) {
                obj['symptomType'] = ApiClient.convertToType(data['symptomType'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
SymptomDTO.prototype['id'] = undefined;

/**
 * @member {String} name
 */
SymptomDTO.prototype['name'] = undefined;

/**
 * @member {module:model/SymptomDTO.SymptomTypeEnum} symptomType
 */
SymptomDTO.prototype['symptomType'] = undefined;





/**
 * Allowed values for the <code>symptomType</code> property.
 * @enum {String}
 * @readonly
 */
SymptomDTO['SymptomTypeEnum'] = {

    /**
     * value: "NUMERICAL"
     * @const
     */
    "NUMERICAL": "NUMERICAL",

    /**
     * value: "STRING"
     * @const
     */
    "STRING": "STRING"
};



export default SymptomDTO;

