/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Symptom model module.
 * @module model/Symptom
 * @version 1.0
 */
class Symptom {
    /**
     * Constructs a new <code>Symptom</code>.
     * All details about a symptom.
     * @alias module:model/Symptom
     */
    constructor() { 
        
        Symptom.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Symptom</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Symptom} obj Optional instance to populate.
     * @return {module:model/Symptom} The populated <code>Symptom</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Symptom();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
Symptom.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Symptom.prototype['name'] = undefined;

/**
 * @member {Number} value
 */
Symptom.prototype['value'] = undefined;






export default Symptom;

