/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TimeLineObject from './TimeLineObject';

/**
 * The TimelineJsonRoot model module.
 * @module model/TimelineJsonRoot
 * @version 1.0
 */
class TimelineJsonRoot {
    /**
     * Constructs a new <code>TimelineJsonRoot</code>.
     * @alias module:model/TimelineJsonRoot
     */
    constructor() { 
        
        TimelineJsonRoot.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TimelineJsonRoot</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TimelineJsonRoot} obj Optional instance to populate.
     * @return {module:model/TimelineJsonRoot} The populated <code>TimelineJsonRoot</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TimelineJsonRoot();

            if (data.hasOwnProperty('timelineObjects')) {
                obj['timelineObjects'] = ApiClient.convertToType(data['timelineObjects'], [TimeLineObject]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/TimeLineObject>} timelineObjects
 */
TimelineJsonRoot.prototype['timelineObjects'] = undefined;






export default TimelineJsonRoot;

