/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PlaceVisit from './PlaceVisit';

/**
 * The TimeLineObject model module.
 * @module model/TimeLineObject
 * @version 1.0
 */
class TimeLineObject {
    /**
     * Constructs a new <code>TimeLineObject</code>.
     * @alias module:model/TimeLineObject
     */
    constructor() { 
        
        TimeLineObject.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TimeLineObject</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TimeLineObject} obj Optional instance to populate.
     * @return {module:model/TimeLineObject} The populated <code>TimeLineObject</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TimeLineObject();

            if (data.hasOwnProperty('placeVisit')) {
                obj['placeVisit'] = PlaceVisit.constructFromObject(data['placeVisit']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/PlaceVisit} placeVisit
 */
TimeLineObject.prototype['placeVisit'] = undefined;






export default TimeLineObject;

